"""empty message

Revision ID: 072db2d8cea9
Revises: 567e902a6c8c
Create Date: 2026-06-08 21:14:56.044438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '072db2d8cea9'
down_revision: Union[str, Sequence[str], None] = '567e902a6c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_index('tg_id_index', 'Users', ['tg_id'], unique=False)
    op.create_table('Channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['Users.tg_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    op.create_index('channels_index', 'Channels', ['channel_id', 'owner_id'], unique=False)
    op.create_table('User_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_plan', sa.Enum('STANDART', 'PRO', 'VIP', name='paymentoptions'), server_default=sa.text("'STANDART'"), nullable=False),
    sa.Column('automatic_buy', sa.Boolean(), nullable=False),
    sa.Column('activate_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.tg_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('user_payment_index', 'User_payments', ['user_id', 'end_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_payment_index', table_name='User_payments')
    op.drop_table('User_payments')
    op.drop_index('channels_index', table_name='Channels')
    op.drop_table('Channels')
    op.drop_index('tg_id_index', table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###
