"""empty message

Revision ID: 0932d9961720
Revises: 
Create Date: 2026-07-03 00:14:53.768809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0932d9961720'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AiNews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('pictureUrl', sa.String(), nullable=True),
    sa.Column('addingDate', sa.Date(), nullable=False),
    sa.Column('dropDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index('title_drop_index_AI', 'AiNews', ['title', 'dropDate'], unique=False)
    op.create_table('ChannelsSettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('posts_count', sa.Integer(), nullable=False),
    sa.Column('theme', sa.Enum('AI_NEWS', 'CRYPTO_NEWS', 'GAMES_NEWS', 'IT_NEWS', 'SCIENCE_NEWS', 'SHOW_BIS_NEWS', 'SPORT_NEWS', 'WORLD_NEWS', 'OWN_FILE', 'AI_POSTS', 'UNDEFINED', name='posttheme'), server_default=sa.text("'UNDEFINED'"), nullable=False),
    sa.Column('is_active_posting', sa.Boolean(), nullable=False),
    sa.Column('resource', sa.Enum('DATABASE', 'FILE', 'AI_POSTS', name='resource'), server_default=sa.text("'DATABASE'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    op.create_table('CryptoCurrencyNews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('pictureUrl', sa.String(), nullable=True),
    sa.Column('addingDate', sa.Date(), nullable=False),
    sa.Column('dropDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index('title_drop_index_crypto', 'CryptoCurrencyNews', ['title', 'dropDate'], unique=False)
    op.create_table('GamesNews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('pictureUrl', sa.String(), nullable=True),
    sa.Column('addingDate', sa.Date(), nullable=False),
    sa.Column('dropDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index('title_drop_index_games', 'GamesNews', ['title', 'dropDate'], unique=False)
    op.create_table('ItTechnologiesNews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('pictureUrl', sa.String(), nullable=True),
    sa.Column('addingDate', sa.Date(), nullable=False),
    sa.Column('dropDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index('title_drop_index_IT', 'ItTechnologiesNews', ['title', 'dropDate'], unique=False)
    op.create_table('ScienceNews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('pictureUrl', sa.String(), nullable=True),
    sa.Column('addingDate', sa.Date(), nullable=False),
    sa.Column('dropDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index('title_drop_index_science', 'ScienceNews', ['title', 'dropDate'], unique=False)
    op.create_table('ShowBisNews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('pictureUrl', sa.String(), nullable=True),
    sa.Column('addingDate', sa.Date(), nullable=False),
    sa.Column('dropDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index('title_drop_index_showbis', 'ShowBisNews', ['title', 'dropDate'], unique=False)
    op.create_table('SportsNews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('pictureUrl', sa.String(), nullable=True),
    sa.Column('addingDate', sa.Date(), nullable=False),
    sa.Column('dropDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index('title_drop_index_sports', 'SportsNews', ['title', 'dropDate'], unique=False)
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_index('tg_id_index', 'Users', ['tg_id'], unique=False)
    op.create_table('WorldNews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('pictureUrl', sa.String(), nullable=True),
    sa.Column('addingDate', sa.Date(), nullable=False),
    sa.Column('dropDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index('title_drop_index_news', 'WorldNews', ['title', 'dropDate'], unique=False)
    op.create_table('Channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['Users.tg_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    op.create_index('channels_index', 'Channels', ['channel_id', 'owner_id'], unique=False)
    op.create_table('User_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_plan', sa.Enum('STANDART', 'PRO', 'VIP', name='paymentoptions'), server_default=sa.text("'STANDART'"), nullable=False),
    sa.Column('automatic_buy', sa.Boolean(), nullable=False),
    sa.Column('pending_plan', sa.Enum('STANDART', 'PRO', 'VIP', name='paymentoptions'), server_default=sa.text("'STANDART'"), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('activate_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.tg_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('user_payment_index', 'User_payments', ['user_id', 'end_date'], unique=False)
    op.create_table('PostsTimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['Channels.channel_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_user_storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.String(length=3600), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['Channels.channel_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('generate_user_storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(length=3600), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['Channels.channel_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generate_user_storage')
    op.drop_table('file_user_storage')
    op.drop_table('PostsTimes')
    op.drop_index('user_payment_index', table_name='User_payments')
    op.drop_table('User_payments')
    op.drop_index('channels_index', table_name='Channels')
    op.drop_table('Channels')
    op.drop_index('title_drop_index_news', table_name='WorldNews')
    op.drop_table('WorldNews')
    op.drop_index('tg_id_index', table_name='Users')
    op.drop_table('Users')
    op.drop_index('title_drop_index_sports', table_name='SportsNews')
    op.drop_table('SportsNews')
    op.drop_index('title_drop_index_showbis', table_name='ShowBisNews')
    op.drop_table('ShowBisNews')
    op.drop_index('title_drop_index_science', table_name='ScienceNews')
    op.drop_table('ScienceNews')
    op.drop_index('title_drop_index_IT', table_name='ItTechnologiesNews')
    op.drop_table('ItTechnologiesNews')
    op.drop_index('title_drop_index_games', table_name='GamesNews')
    op.drop_table('GamesNews')
    op.drop_index('title_drop_index_crypto', table_name='CryptoCurrencyNews')
    op.drop_table('CryptoCurrencyNews')
    op.drop_table('ChannelsSettings')
    op.drop_index('title_drop_index_AI', table_name='AiNews')
    op.drop_table('AiNews')
    # ### end Alembic commands ###
