"""empty message

Revision ID: 567e902a6c8c
Revises: 
Create Date: 2026-06-06 14:03:51.219797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '567e902a6c8c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AiNews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('pictureUrl', sa.String(), nullable=True),
    sa.Column('addingDate', sa.Date(), nullable=False),
    sa.Column('dropDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index('title_drop_index_AI', 'AiNews', ['title', 'dropDate'], unique=False)
    op.create_table('CryptoCurrencyNews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('pictureUrl', sa.String(), nullable=True),
    sa.Column('addingDate', sa.Date(), nullable=False),
    sa.Column('dropDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index('title_drop_index_crypto', 'CryptoCurrencyNews', ['title', 'dropDate'], unique=False)
    op.create_table('GamesNews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('pictureUrl', sa.String(), nullable=True),
    sa.Column('addingDate', sa.Date(), nullable=False),
    sa.Column('dropDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index('title_drop_index_games', 'GamesNews', ['title', 'dropDate'], unique=False)
    op.create_table('ItTechnologiesNews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('pictureUrl', sa.String(), nullable=True),
    sa.Column('addingDate', sa.Date(), nullable=False),
    sa.Column('dropDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index('title_drop_index_IT', 'ItTechnologiesNews', ['title', 'dropDate'], unique=False)
    op.create_table('ScienceNews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('pictureUrl', sa.String(), nullable=True),
    sa.Column('addingDate', sa.Date(), nullable=False),
    sa.Column('dropDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index('title_drop_index_science', 'ScienceNews', ['title', 'dropDate'], unique=False)
    op.create_table('ShowBisNews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('pictureUrl', sa.String(), nullable=True),
    sa.Column('addingDate', sa.Date(), nullable=False),
    sa.Column('dropDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index('title_drop_index_showbis', 'ShowBisNews', ['title', 'dropDate'], unique=False)
    op.create_table('SportsNews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('pictureUrl', sa.String(), nullable=True),
    sa.Column('addingDate', sa.Date(), nullable=False),
    sa.Column('dropDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index('title_drop_index_sports', 'SportsNews', ['title', 'dropDate'], unique=False)
    op.create_table('WorldNews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('pictureUrl', sa.String(), nullable=True),
    sa.Column('addingDate', sa.Date(), nullable=False),
    sa.Column('dropDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index('title_drop_index_news', 'WorldNews', ['title', 'dropDate'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('title_drop_index_news', table_name='WorldNews')
    op.drop_table('WorldNews')
    op.drop_index('title_drop_index_sports', table_name='SportsNews')
    op.drop_table('SportsNews')
    op.drop_index('title_drop_index_showbis', table_name='ShowBisNews')
    op.drop_table('ShowBisNews')
    op.drop_index('title_drop_index_science', table_name='ScienceNews')
    op.drop_table('ScienceNews')
    op.drop_index('title_drop_index_IT', table_name='ItTechnologiesNews')
    op.drop_table('ItTechnologiesNews')
    op.drop_index('title_drop_index_games', table_name='GamesNews')
    op.drop_table('GamesNews')
    op.drop_index('title_drop_index_crypto', table_name='CryptoCurrencyNews')
    op.drop_table('CryptoCurrencyNews')
    op.drop_index('title_drop_index_AI', table_name='AiNews')
    op.drop_table('AiNews')
    # ### end Alembic commands ###
